### ISSUE TITLE
Finish filling out Risks on the project proposal

### ISSUE THREAD

**Issue by LucasMali** [MSU-CS4360-WhiteHat/ecommerce-scam-detector#16]
We need to finish filling out the Risks on the project proposal.

**Comment by corywilson88** [comment]
Added the following Risk Analysis to our Project Plan:

Risks Analysis 

 

We will follow these four steps: 

1. Risk identification: We will use brainstorming sessions, and during them the team will  consider potential risks related to project scope, schedule, budget, technology, and human factors. 

  

2. Risk assessment: After risks have been identified, we need to rank them in terms of their impact on the project and their likelihood of occurring. This information can be used to prioritize risks and develop a risk mitigation plan. 

  

3. Risk mitigation: We will establish best practices, conducting regular code reviews, potentially use testing tools as needed, and implementing a continuous integration and continuous delivery (CI/CD) pipeline. 

  

4. Risk monitoring: This includes monitoring the progress of risk mitigation activities, updating the GitHub Project with new information and adjusting the risk mitigation plan as needed. 

 

The one foreseen risk is the conversion of the extension from Chrome/Firefox to Safari may prove to be difficult. As of right now, we have not hit any blockers, but we are keeping an eye on any of the restrictions Apple has implemented for Safari Extensions (https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility). The level of this risk would be classified as “Easy.”  

 

To help mitigate unforeseen security risks, we have implemented sonarcloud as a code sniffer. A code sniffer is a type of software tool that automatically checks source code for compliance with coding standards and best practices. The purpose of a code sniffer is to help ensure that the code is clean, consistent, and free of common coding errors or potential security vulnerabilities. 

 

We will update the project plan / Presentations as new unforeseen risks to the overall project arise.
