### ISSUE TITLE
Research Safari Build

### ISSUE THREAD

**Issue by thrandale** [MSU-CS4360-WhiteHat/ecommerce-scam-detector#8]
Do some research into whether or not we would need a separate code base for safari or if the chrome/firefox code can be easily used or transformed into a safari extension

**Comment by corywilson88** [comment]
@thrandale Not yet. I can create a new branch with what we have so far and do some testing there this week

**Comment by corywilson88** [comment]
@thrandale @LucasMali 

Whenever you get a change, take a look at the PR: https://github.com/MSU-CS4360-WhiteHat/ecommerce-scam-detector/pull/20
